//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightTicketManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUYENBAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHUYENBAY()
        {
            this.CHITIETHANGVEs = new HashSet<CHITIETHANGVE>();
            this.CTDOANHTHUTHANGs = new HashSet<CTDOANHTHUTHANG>();
            this.CTSANBAYTRUNGGIANs = new HashSet<CTSANBAYTRUNGGIAN>();
        }
    
        public string MaChuyenBay { get; set; }
        public string MaTuyenBay { get; set; }
        public string MaSanBayDi { get; set; }
        public string MaSanBayDen { get; set; }
        public string MaMayBay { get; set; }
        public System.DateTime NgayBay { get; set; }
        public System.TimeSpan GioKhoiHanh { get; set; }
        public double ThoiLuong { get; set; }
        public decimal DonGia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHANGVE> CHITIETHANGVEs { get; set; }
        public virtual MAYBAY MAYBAY { get; set; }
        public virtual SANBAY SANBAY { get; set; }
        public virtual SANBAY SANBAY1 { get; set; }
        public virtual TUYENBAY TUYENBAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDOANHTHUTHANG> CTDOANHTHUTHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTSANBAYTRUNGGIAN> CTSANBAYTRUNGGIANs { get; set; }
    }
}
