//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightTicketManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOANHTHUNAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOANHTHUNAM()
        {
            this.CTDOANHTHUNAMs = new HashSet<CTDOANHTHUNAM>();
        }
    
        public int NAM { get; set; }
        public Nullable<decimal> TONGDOANHTHUNAM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDOANHTHUNAM> CTDOANHTHUNAMs { get; set; }
    }
}
