//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightTicketManagement.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QUANLYBANVECHUYENBAYEntities : DbContext
    {
        public QUANLYBANVECHUYENBAYEntities()
            : base("name=QUANLYBANVECHUYENBAYEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHITIETHANGVE> CHITIETHANGVEs { get; set; }
        public virtual DbSet<CHUYENBAY> CHUYENBAYs { get; set; }
        public virtual DbSet<CTDOANHTHUNAM> CTDOANHTHUNAMs { get; set; }
        public virtual DbSet<CTDOANHTHUTHANG> CTDOANHTHUTHANGs { get; set; }
        public virtual DbSet<CTSANBAYTRUNGGIAN> CTSANBAYTRUNGGIANs { get; set; }
        public virtual DbSet<DANHSACHGHECUAMAYBAY> DANHSACHGHECUAMAYBAYs { get; set; }
        public virtual DbSet<DOANHTHUNAM> DOANHTHUNAMs { get; set; }
        public virtual DbSet<HANGMAYBAY> HANGMAYBAYs { get; set; }
        public virtual DbSet<HANGVE> HANGVEs { get; set; }
        public virtual DbSet<HANHKHACH> HANHKHACHes { get; set; }
        public virtual DbSet<MAYBAY> MAYBAYs { get; set; }
        public virtual DbSet<PHIEUDATCHO> PHIEUDATCHOes { get; set; }
        public virtual DbSet<QUOCGIA> QUOCGIAs { get; set; }
        public virtual DbSet<SANBAY> SANBAYs { get; set; }
        public virtual DbSet<TUYENBAY> TUYENBAYs { get; set; }
        public virtual DbSet<VECHUYENBAY> VECHUYENBAYs { get; set; }
        public virtual DbSet<THAMSO> THAMSOes { get; set; }
        public virtual DbSet<TAIKHOAN1> TAIKHOAN1 { get; set; }
    }
}
