//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightTicketManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAMSO
    {
        public byte SoSanBayTrungGianToiDa { get; set; }
        public int ThoiGianBayToiThieu { get; set; }
        public int ThoiGianDungToiThieu { get; set; }
        public int ThoiGianDungToiDa { get; set; }
        public byte ThoiGianDatVeChamNhat { get; set; }
        public byte ThoiGianHuyVeDatVe { get; set; }
    }
}
