//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightTicketManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUYENBAY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TUYENBAY()
        {
            this.CHUYENBAYs = new HashSet<CHUYENBAY>();
        }
    
        public string MaTuyenBay { get; set; }
        public string MaQuocGiaDi { get; set; }
        public string MaQuocGiaDen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHUYENBAY> CHUYENBAYs { get; set; }
        public virtual QUOCGIA QUOCGIA { get; set; }
        public virtual QUOCGIA QUOCGIA1 { get; set; }
    }
}
