//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightTicketManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VECHUYENBAY
    {
        public string MaVe { get; set; }
        public System.DateTime NgayXuatVe { get; set; }
        public string MaChuyenBay { get; set; }
        public string MaHangVe { get; set; }
        public string MaHanhKhach { get; set; }
        public string MaGhe { get; set; }
    
        public virtual CHITIETHANGVE CHITIETHANGVE { get; set; }
        public virtual DANHSACHGHECUAMAYBAY DANHSACHGHECUAMAYBAY { get; set; }
        public virtual HANHKHACH HANHKHACH { get; set; }
    }
}
